### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by scsijon** [GregorR/snowflake#1]
Any chance of updating this for the latest 'stuff' like kernel, gcc and the like. It's interesting enough that it looks like it could be used for control in a container system situation without having to add all those complex tools and controls normally needed.

**Comment by sskras** [comment]
ping

**Comment by GregorR** [comment]
Unlikely; I lost interest in this project. Suppose I should archive it. The underlying technology should work fine, so if somebody's interested, it shouldn't be too difficult to bring it up to date. I'd be happy to help/consult on such an effort.
